### ISSUE TITLE
User can not close tooltip 

### ISSUE THREAD

**Issue by svetlanaStupakova** [snieking/chromunity#51]
1. Create new Topic
2. Enter incorrect data
3. Click 'Create Topic' button
4. Close red tooltip by 'X' button

Actual result: Tooltip is not closed
Expected result: There is no 'X' or tooltip can be closed by 'X' button

https://drive.google.com/open?id=1fJr_mXmQyKZi9czkBPq6cVdnm06MPIXU

**Comment by snieking** [comment]
Resolved
