### ISSUE TITLE
The data updates incorrect if user edits topic

### ISSUE THREAD

**Issue by svetlanaStupakova** [snieking/chromunity#52]
1. Create topic
2. Click on topic. Click 'Edit' button
3. Enter new text. Click 'Send' button

Actual result: old data is shown 
Expected result: new data is shown

https://drive.google.com/open?id=1xIDIz-fsMLmAb97uscCqlZPOaBZs4TTY

**Comment by snieking** [comment]
Closes the wrong ticket, this one is not resolved yet.
