### ISSUE TITLE
The followed user appears in the list after updating page

### ISSUE THREAD

**Issue by svetlanaStupakova** [snieking/chromunity#53]
1. Find user
2. Click on 'heart' to follow user
3. Click on 'Users' in the bottom menu 

Actual result: The user is not in the list
Expected result: The user is in the list

https://drive.google.com/open?id=1eyqIScyTPEC9aKuqf9l16HQ9_ib-QVkU

**Comment by snieking** [comment]
Should work correctly now. Important to know is that a user wall is cached for 60 seconds, so if you only recently opened the user wall, the newly followed users will start showing up after 60 seconds.
