### ISSUE TITLE
The number of stars is not saved

### ISSUE THREAD

**Issue by svetlanaStupakova** [snieking/chromunity#54]
1. Find Topic
2. Click on it
3. Click Star 
4. Go to Home page
5. Find the Topic from the 1st step

Actual result: The number of stars is not changed 
Expected result: The number of stars is saved 

https://drive.google.com/open?id=1C62H7KHqkCZLeD1tVIm1eyvOwwV4lYAj

**Comment by snieking** [comment]
Should work better now

**Comment by svetlanaStupakova** [comment]
Verified in Google Chrome
