### ISSUE TITLE
The user states in the Favorites list

### ISSUE THREAD

**Issue by svetlanaStupakova** [snieking/chromunity#55]
1.Find user
2.Click on 'heart' to follow user
3.Click on 'Users' icon in the menu
4. Click on user to see user's info. Click 'heart' to stop following user
5. Wait 60 seconds
6. Click on 'Users' icon in the menu
Actual result: The user is in the list
Expected result: The user is not in the list

see also https://github.com/snieking/chromunity/issues/53

https://drive.google.com/open?id=167T2kYjHhE51h9xbXBQ0G2ugF6O7vLyQ

**Comment by snieking** [comment]
Should be resolved now. Caches are now emptied on toggling the following of a user. The same bug was true for channels as well, which should as well be resolved now.
